version: "3.8"
services:
  web:
    working_dir: /workspace
    command: >-
      bash -lc "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    read_only: false
    volumes:
      - type: bind
        source: c:\\Users\\Filip\\Desktop\\Django
        target: /workspace

  db:
    # inherit base settings; no override
