name: Nightly DB Backup

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Set timestamp
        id: ts
        run: echo "ts=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
      - name: Install pg client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Dump database
        env:
          PGHOST: ${{ secrets.PGHOST }}
          PGPORT: ${{ secrets.PGPORT }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
        run: |
          pg_dump -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" -F c -f dump-${{ steps.ts.outputs.ts }}.sqlc
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: db-backup-${{ steps.ts.outputs.ts }}
          path: dump-${{ steps.ts.outputs.ts }}.sqlc
