name: Publish Docker (prod)

on:
  workflow_run:
    workflows: ["CI (prod)"]
    types:
      - completed

permissions:
  contents: read
  packages: write

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Extract version (semver)
        id: extract_version
        shell: bash
        run: |
          VERSION=$(python -c "import io,re; s=io.open('Vigar/settings.py','r',encoding='utf-8').read(); m=re.search(r'VERSION\"\\s*:\\s*\"([^\"]+)\"', s); print(m.group(1) if m else '0.0.0')")
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image (prod)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/vigar:prod-latest
            ghcr.io/${{ github.repository_owner }}/vigar:prod-${{ github.event.workflow_run.head_sha }}
            ghcr.io/${{ github.repository_owner }}/vigar:prod-${{ steps.extract_version.outputs.version }}
