name: Renovate

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  renovate:
    name: Run Renovate
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Self‑hosted Renovate
      uses: renovatebot/github-action@v43.0.4
      with:
        token: ${{ secrets.RENOVATE_TOKEN1 }}
        configurationFile: renovate-config.js

