name: Renovate

on:
  workflow_run:
    workflows: ["CI (dev)"]
    types: [completed]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  renovate:
    name: Run Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (workflow_run)
        if: ${{ github.event_name == 'workflow_run' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Checkout (manual)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/checkout@v4

      - name: Scan for critical vulnerabilities (Trivy)
        if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'dev' }}
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          scanners: vuln
          ignore-unfixed: true
          severity: CRITICAL
          exit-code: '1'
          format: table
          hide-progress: true

      - name: Self-hosted Renovate
        if: >
          ${{
            (github.event_name == 'workflow_run' &&
             github.event.workflow_run.conclusion == 'success' &&
             github.event.workflow_run.event == 'push' &&
             github.event.workflow_run.head_branch == 'dev')
            || github.event_name == 'workflow_dispatch'
          }}
        uses: renovatebot/github-action@v43.0.4

        with:
          token: ${{ secrets.RENOVATE_TOKEN1 }}
          configurationFile: renovate-config.js
        env:
          LOG_LEVEL: info
          RENOVATE_REPOSITORIES: ${{ github.repository }}   # 👈 OVO DODAJ
